version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
   
  go:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=test

# version: '3.8'

# services:
#   go-app:
#     image: golang:latest
#     build:
#       context: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
#     environment:
#       - MYSQL_HOST=db
#       - MYSQL_PORT=3306
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=root
#       - MYSQL_DB=test
#     command: sh -c "go build -o main && ./main"

#   db:
#     image: mysql:latest
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test
